### ISSUE TITLE
Add no Sort

### ISSUE THREAD

**Issue by broerse** [lazybensch/ember-cli-filter-by-query#7]
I like to be able to not sort. Perhaps I can write a PR but how do we like to pass a nosort flag? My code:

``` javascript
sifter = new Sifter(input);
sifter.getSortFunction = function() {
  return null;
};
result = sifter.search(query, options);
```

**Comment by lazybensch** [comment]
@broerse i think this is a great idea!
My proposal would be to pass it inside the `additional options` hash described [here](https://github.com/lazybensch/ember-cli-filter-by-query#additional-options).
One caveat to keep in mind though is that we are passing that option hash directly through to sifter ([after populating it](https://github.com/lazybensch/ember-cli-filter-by-query/blob/master/addon/util/filter.js#L22-29)) so when we pass a `sort` key you also need to remove it from the hash again.

I would like if it then can be used like this:

``` js
filteredFriends: computedFilterByQuery( 'friends', 'name', 'query', {sort: false })
```

Thanks for your contribution so far :) if you need any additional help with the PR or have a better idea about the interface please let me know

**Comment by broerse** [comment]
My PR: https://github.com/lazybensch/ember-cli-filter-by-query/pull/8

**Comment by lazybensch** [comment]
@broerse thx a lot! your changes are published under `ember-cli-filter-by-query@1.1.0`

**Comment by broerse** [comment]
@lazybensch Thanks!

**Comment by broerse** [comment]
@lazybensch Don't know if it is necessary but https://github.com/lazybensch/ember-cli-filter-by-query/releases is still v1.0.2

**Comment by lazybensch** [comment]
oh thats not a problem i just forgot to push the new tag to Github. but when you publish a node package you do it from your local repo so all is good :)
